/* do not change this file, it is auto generated by storybook. */

import {
  configure,
  addDecorator,
  addParameters,
  addArgsEnhancer,
  clearDecorators,
} from '@storybook/react-native';

import '@storybook/addon-ondevice-controls/register';
import '@storybook/addon-ondevice-actions/register';
import '@storybook/addon-ondevice-backgrounds/register';
import '@storybook/addon-ondevice-notes/register';

import { argsEnhancers } from '@storybook/addon-ondevice-controls/dist/preset/addArgsEnhancers';

import { decorators } from './preview';

if (decorators) {
  if (__DEV__) {
    // stops the warning from showing on every HMR
    clearDecorators();
  }
  decorators.forEach(decorator => addDecorator(decorator));
}

addArgsEnhancer(...argsEnhancers);

const getStories = () => {
  return [
    // Button stories
    require('../src/components/Button/Button.stories.tsx'),
    require('../src/components/Card/Card.stories.tsx'),
    require('../src/components/TextInput/TextInput.stories.tsx'),
  ];
};

configure(getStories, module, false);

export { configure, addDecorator, addParameters, addArgsEnhancer, clearDecorators };
